# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "dev-terragrunt-state-demo-bucket"
    dynamodb_table = "my-dev-lock-table"
    encrypt        = true
    key            = "DEV/VPC/terraform.tfstate"
    region         = "us-east-1"
  }
}
